// <auto-generated />
namespace Pawze.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedboxIdfromsubscriptiondomainandmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedboxIdfromsubscriptiondomainandmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201603011808513_removed boxId from subscription domain and model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
